### ISSUE TITLE
Jcb vendor is returned when should be Unknown

### ISSUE THREAD

**Issue by kakarotto67** [julia-hrytsyk/CardValidator#3]
Pass 35301113333000001 into IsCreditCardNumberValid or GetCreditCardVendor
Expected result: false or Unknown as this number has 17 characters (16 is valid for Jcb, https://www.wikiwand.com/en/Bank_card_number)
Actual result: true and Jcb

**Comment by cyberoSpirit** [comment]
Fixed.

**Comment by kakarotto67** [comment]
IsCreditCardNumberValid still returns true for "35301113333000001"
