### ISSUE TITLE
Visa is returned when should be Unknown

### ISSUE THREAD

**Issue by kakarotto67** [julia-hrytsyk/CardValidator#4]
Pass "41111111111111112" into GetCreditCardVendor method
Expected result: Unknown (as this number isn't valid, try to pass it into your IsCreditCardNumberValid method and you will see it)
Actual result: Visa

**Comment by kakarotto67** [comment]
The same issue with "50000000000006114" number. It isn't valid (pass it into your IsCreditCardNumberValid method), but your GetCreditCardVendor returns Maestro.

**Comment by kakarotto67** [comment]
And the same with "3434343434343433", it isn't valid, but your method returns AmericanExpress.

**Comment by cyberoSpirit** [comment]
Fixed.
