### ISSUE TITLE
IsCreditCardNumberValid return false for valid card numbers

### ISSUE THREAD

**Issue by kakarotto67** [julia-hrytsyk/CardValidator#5]
Pass the following card numbers into your IsCreditCardNumberValid method (they are all valid, check [this](https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm), [this](http://support.worldpay.com/support/kb/bg/testandgolive/tgl5103.html), and [this](http://www.securetrading.com/resources/test-card-numbers-2/)):
"3411 3411 3411 347"
"3530 1113 3330 0000"
"3566 0020 2036 0505"
"3782 8224 6310 005"
"4012 8888 8888 1881"
"4111 1111 1111 1111"
"4222 2222 222 22"
"5000 0000 0000 0611"
"5105 1051 0510 5100"
"555 5555 5555 4444"
Expected result: true (for each card number from above)
Actual result: false (for each card number from above)

**Comment by cyberoSpirit** [comment]
I got "valid" for all this numbers

**Comment by kakarotto67** [comment]
Strange, I get "false" for all these numbers.
Please, run the following unit test (pass your method into test in the way as it appears in your solution):
        [TestCase("3411 3411 3411 347")]
        [TestCase("3530 1113 3330 0000")]
        [TestCase("3566 0020 2036 0505")]
        [TestCase("3782 8224 6310 005")]
        [TestCase("4012 8888 8888 1881")]
        [TestCase("4111 1111 1111 1111")]
        [TestCase("4222 2222 222 22")]
        [TestCase("5000 0000 0000 0611")]
        [TestCase("5105 1051 0510 5100")]
        [TestCase("555 5555 5555 4444")]
        public void IsCreditCardNumberValid_True(string number)
        {
            Assert.IsTrue(CreditCardUtility.IsCreditCardNumberValid(number));
        }

**Comment by cyberoSpirit** [comment]
I find mistake (previously I have removed white spaces in **main()** method that's why I got "valid" result).

But what about the last test case, let's calculate:
555           5555    5555    4444
5+1+5  + 1+5+1+5 + 1+5+1+5 + 8+4+8+4
   11      +        12     +      12     +       24  =   59

59 % 2  != 0

That's the reason why this test can't be passed with function.
