### ISSUE TITLE
Issues with next number & incorrect validation

### ISSUE THREAD

**Issue by kakarotto67** [julia-hrytsyk/CardValidator#7]
Last issues you have:
GenerateNextCreditCardNumber doesn't generate valid next numbers for these cards:
"343434343434343" (next should be "343434343434350")
"343434343434392" (next should be "343434343434400")
"343434343434590" (next should be "343434343434608")

And IsCreditCardNumberValid still returns true for "35301113333000001", but should be false, as this number isn't valid (see comment to [this ](https://github.com/julia-hrytsyk/CardValidator/issues/3#issuecomment-217631749)issue).

**Comment by cyberoSpirit** [comment]
Fixed
